languageCode = "en-us"
title = "My dear diary"
theme = "anubis"
paginate = 4
baseURL = 'https://yaroslavyaroslav.github.io/'

# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT: true

[author]
name = "Yaroslav Yashin"

[menu]

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Yaroslav Yashin"
email = 'caimans-spurs-0u@icloud.com' # used for microformats
description = "Blog about AI, Swift and Web3. In this particular order."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
# style = 'light-without-switcher'
readMore = false
rssAsSocialIcon = true

# utteranc.es support
utterancesRepo = "yaroslavyaroslav/yaroslavyaroslav.github.io"  # mandatory
utterancesTheme = "github-dark" # optional
utterancesIssue = "url" # optional
utterancesLabel = "🧵" # optional

[[params.social]]
id = "twitter"
url = "https://twitter.com/Yaroslav_Ya"

[[params.social]]
id = "github"
url = "https://github.com/yaroslavyaroslav"

[[params.social]]
id = 'linkedin'
url = 'https://www.linkedin.com/in/yaroslav-yashin-65706083/'

[webmentions]
login = 'yaroslavyaroslav.github.io'
pingback = true

