languageCode = "en-us"
title = "My dear diary"
theme = "anubis"
paginate = 4
baseURL = 'https://yaroslavyaroslav.github.io/'

# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT: true

[author]
name = "Yaroslav Yashin"

[menu]

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Yaroslav Yashin"
email = 'caimans-spurs-0u@icloud.com' # used for microformats
description = "Blog about AI, Swift and Web3. In this particular order."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
# style = 'light-without-switcher'
readMore = false
readNextPosts = 2
rssAsSocialIcon = true

# params:
#   # avatar: "/images/me.png" # used for microformats
#   # Uncomment if you need this
#   # images:
#   #   - images/og-featured.png # relative path to "static" directory
#   # customCSS:
#   #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
#   # customJS:
#   #   - js/main.js # relative path to "assets" directory

#   # # utteranc.es support
#   # utterancesRepo: ""  # mandatory
#   # utterancesTheme: "" # optional
#   # utterancesIssue: "" # optional
#   # utterancesLabel: "" # optional
#   # # isso support
#   # isso:
#   #   enabled: true # mandatory
#   #   data: "https://comments.example.com/" # mandatory
#   #   jsLocation: "https://comments.example.com/js/embed.min.js" # mandatory
#   #   css: true # optional
#   #   lang: "de" # optional
#   #   replyToSelf: true # mandatory
#   #   requireAuthor: true # mandatory
#   #   requireEmail: true # mandatory
#   #   id: "thread-id" # optional
#   #   avatar: true # optional
#   #   avatar-bg: "#f0f0f0" # optional
#   #   feed: false # optional
#   # graphcommentId: ""
#   # webmentions:
#   #   url: https://yourdomain.com/webemntions/receive
#   #   login: hugo-theme-anubis
#   #   pingback: true

[[params.social]]
id = "twitter"
url = "https://twitter.com/Yaroslav_Ya"

[[params.social]]
id = "github"
url = "https://github.com/yaroslavyaroslav"

[[params.social]]
id = 'linkedin'
url = 'https://www.linkedin.com/in/yaroslav-yashin-65706083/'
